USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW VW_ADMISSION_SUMMARY AS
SELECT
    F.ADMISSION_ID,
    D.FULL_DATE AS ADMISSION_DATE,
    DD.FULL_DATE AS DISCHARGE_DATE,

    P.PATIENT_ID,
    P.GENDER,
    P.BLOOD_GROUP,
    P.CITY,

    DEP.DEPARTMENT_NAME,
    DS.DISEASE_NAME,
    W.WARD_NAME,

    F.ADMISSION_TYPE,
    F.ADMISSION_STATUS,
    F.BED_ID,
    F.LENGTH_OF_STAY

FROM FACT_ADMISSION F

INNER JOIN DIM_DATE D
    ON F.ADMISSION_DATE_KEY = D.DATE_KEY

LEFT JOIN DIM_DATE DD
    ON F.DISCHARGE_DATE_KEY = DD.DATE_KEY

INNER JOIN DIM_PATIENT P
    ON F.PATIENT_KEY = P.PATIENT_KEY

INNER JOIN DIM_DEPARTMENT DEP
    ON F.DEPARTMENT_KEY = DEP.DEPARTMENT_KEY

INNER JOIN DIM_DISEASE DS
    ON F.DISEASE_KEY = DS.DISEASE_KEY

INNER JOIN DIM_WARD W
    ON F.WARD_KEY = W.WARD_KEY;
    