-- ============================================================
-- File       : vw_hospital_revenue.sql
-- Purpose    : Hospital Revenue Analytics
-- Layer      : REPORTING
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW VW_HOSPITAL_REVENUE AS
SELECT
    F.BILL_ID,

    D.FULL_DATE AS BILL_DATE,

    A.ADMISSION_ID,

    DEP.DEPARTMENT_NAME,

    P.PATIENT_ID,

    F.TOTAL_AMOUNT,
    F.INSURANCE_COVERED_AMOUNT,
    F.PATIENT_PAYABLE_AMOUNT,

    F.PAYMENT_STATUS,
    F.PAYMENT_MODE

FROM FACT_BILLING F

INNER JOIN DIM_DATE D
    ON F.BILL_DATE_KEY = D.DATE_KEY

INNER JOIN FACT_ADMISSION A
    ON F.ADMISSION_KEY = A.ADMISSION_KEY

INNER JOIN DIM_DEPARTMENT DEP
    ON A.DEPARTMENT_KEY = DEP.DEPARTMENT_KEY

INNER JOIN DIM_PATIENT P
    ON F.PATIENT_KEY = P.PATIENT_KEY;


