-- ============================================================
-- File       : vw_insurance_coverage.sql
-- Purpose    : Insurance Coverage Analytics
-- Layer      : REPORTING
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW VW_INSURANCE_COVERAGE AS
SELECT
    IP.INSURANCE_PROVIDER_ID,
    IP.PROVIDER_NAME,

    COUNT(DISTINCT B.PATIENT_KEY) AS INSURED_PATIENTS,

    ROUND(
        AVG(BPI.COVERAGE_PERCENTAGE),
        2
    ) AS AVG_COVERAGE_PERCENTAGE,

    MIN(BPI.COVERAGE_PERCENTAGE) AS MIN_COVERAGE_PERCENTAGE,

    MAX(BPI.COVERAGE_PERCENTAGE) AS MAX_COVERAGE_PERCENTAGE

FROM BRIDGE_PATIENT_INSURANCE BPI

INNER JOIN DIM_INSURANCE_PROVIDER IP
    ON BPI.INSURANCE_PROVIDER_KEY = IP.INSURANCE_PROVIDER_KEY

INNER JOIN DIM_PATIENT P
    ON BPI.PATIENT_KEY = P.PATIENT_KEY

LEFT JOIN FACT_BILLING B
    ON B.PATIENT_KEY = P.PATIENT_KEY

GROUP BY
    IP.INSURANCE_PROVIDER_ID,
    IP.PROVIDER_NAME;