-- ============================================================
-- File       : vw_prescription_analytics.sql
-- Purpose    : Prescription Analytics
-- Layer      : REPORTING
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW VW_PRESCRIPTION_ANALYTICS AS
SELECT
    D.DRUG_ID,
    D.DRUG_NAME,
    D.BRAND_NAME,
    D.DRUG_CATEGORY,
    D.MANUFACTURER_NAME,

    DEP.DEPARTMENT_NAME,

    COUNT(*) AS PRESCRIPTION_COUNT,

    COUNT(DISTINCT F.PATIENT_KEY) AS UNIQUE_PATIENTS,

    ROUND(AVG(F.DURATION_DAYS), 2) AS AVG_DURATION_DAYS,

    MIN(D.UNIT_COST) AS UNIT_COST

FROM FACT_PRESCRIPTION F

INNER JOIN DIM_DRUG D
    ON F.DRUG_KEY = D.DRUG_KEY

INNER JOIN FACT_ADMISSION A
    ON F.ADMISSION_KEY = A.ADMISSION_KEY

INNER JOIN DIM_DEPARTMENT DEP
    ON A.DEPARTMENT_KEY = DEP.DEPARTMENT_KEY

GROUP BY
    D.DRUG_ID,
    D.DRUG_NAME,
    D.BRAND_NAME,
    D.DRUG_CATEGORY,
    D.MANUFACTURER_NAME,
    DEP.DEPARTMENT_NAME;