-- ============================================================
-- File       : bridge_patient_insurance.sql
-- Purpose    : Bridge Patient and Insurance Provider
-- Layer      : ANALYTICS
-- Grain      : One row per patient insurance policy
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE BRIDGE_PATIENT_INSURANCE (
    PATIENT_INSURANCE_KEY NUMBER AUTOINCREMENT,
    PATIENT_INSURANCE_ID NUMBER,

    PATIENT_KEY NUMBER,
    INSURANCE_PROVIDER_KEY NUMBER,

    POLICY_NUMBER VARCHAR(100),
    COVERAGE_PERCENTAGE NUMBER(5,2),
    POLICY_START_DATE DATE,
    POLICY_END_DATE DATE,

    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO BRIDGE_PATIENT_INSURANCE (
    PATIENT_INSURANCE_ID,
    PATIENT_KEY,
    INSURANCE_PROVIDER_KEY,
    POLICY_NUMBER,
    COVERAGE_PERCENTAGE,
    POLICY_START_DATE,
    POLICY_END_DATE,
    LOAD_TIMESTAMP
)
SELECT
    PI.PATIENT_INSURANCE_ID,

    P.PATIENT_KEY,

    IP.INSURANCE_PROVIDER_KEY,

    PI.POLICY_NUMBER,

    PI.COVERAGE_PERCENTAGE,

    PI.POLICY_START_DATE,

    PI.POLICY_END_DATE,

    CURRENT_TIMESTAMP()

FROM CURATED.CUR_PATIENT_INSURANCE PI

INNER JOIN DIM_PATIENT P
    ON PI.PATIENT_ID = P.PATIENT_ID

INNER JOIN DIM_INSURANCE_PROVIDER IP
    ON PI.INSURANCE_PROVIDER_ID = IP.INSURANCE_PROVIDER_ID

WHERE PI.PATIENT_INSURANCE_ID IS NOT NULL;