-- ============================================================
-- File       : fact_diagnostic.sql
-- Purpose    : Create Diagnostic Fact Table
-- Layer      : ANALYTICS
-- Grain      : One row per patient diagnostic event
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE FACT_DIAGNOSTIC (
    DIAGNOSTIC_KEY NUMBER AUTOINCREMENT,
    PATIENT_DIAGNOSTIC_ID NUMBER,

    PATIENT_KEY NUMBER,
    ADMISSION_KEY NUMBER,
    DOCTOR_KEY NUMBER,
    TEST_KEY NUMBER,

    TEST_DATE_KEY NUMBER(8,0),

    RESULT_STATUS VARCHAR(30),

    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO FACT_DIAGNOSTIC (
    PATIENT_DIAGNOSTIC_ID,
    PATIENT_KEY,
    ADMISSION_KEY,
    DOCTOR_KEY,
    TEST_KEY,
    TEST_DATE_KEY,
    RESULT_STATUS,
    LOAD_TIMESTAMP
)
SELECT
    PD.PATIENT_DIAGNOSTIC_ID,

    A.PATIENT_KEY,

    A.ADMISSION_KEY,

    D.DOCTOR_KEY,

    T.TEST_KEY,

    TO_NUMBER(TO_CHAR(PD.TEST_DATE, 'YYYYMMDD')),

    UPPER(TRIM(PD.RESULT_STATUS)),

    CURRENT_TIMESTAMP()

FROM CURATED.CUR_PATIENT_DIAGNOSTIC PD

INNER JOIN FACT_ADMISSION A
    ON PD.ADMISSION_ID = A.ADMISSION_ID

INNER JOIN DIM_DOCTOR D
    ON PD.DOCTOR_ID = D.DOCTOR_ID

INNER JOIN DIM_DIAGNOSTIC_TEST T
    ON PD.TEST_ID = T.TEST_ID

WHERE PD.PATIENT_DIAGNOSTIC_ID IS NOT NULL;