-- ============================================================
-- File       : fact_billing.sql
-- Purpose    : Create Billing Fact Table
-- Layer      : ANALYTICS
-- Grain      : One row per bill
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE FACT_BILLING (
    BILLING_KEY NUMBER AUTOINCREMENT,
    BILL_ID NUMBER,

    ADMISSION_KEY NUMBER,
    PATIENT_KEY NUMBER,

    BILL_DATE_KEY NUMBER(8,0),

    TOTAL_AMOUNT NUMBER(12,2),
    INSURANCE_COVERED_AMOUNT NUMBER(12,2),
    PATIENT_PAYABLE_AMOUNT NUMBER(12,2),

    PAYMENT_STATUS VARCHAR(30),
    PAYMENT_MODE VARCHAR(30),

    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO FACT_BILLING (
    BILL_ID,
    ADMISSION_KEY,
    PATIENT_KEY,
    BILL_DATE_KEY,
    TOTAL_AMOUNT,
    INSURANCE_COVERED_AMOUNT,
    PATIENT_PAYABLE_AMOUNT,
    PAYMENT_STATUS,
    PAYMENT_MODE,
    LOAD_TIMESTAMP
)
SELECT
    B.BILL_ID,

    A.ADMISSION_KEY,

    A.PATIENT_KEY,

    TO_NUMBER(TO_CHAR(B.BILL_DATE, 'YYYYMMDD')),

    B.TOTAL_AMOUNT,

    B.INSURANCE_COVERED_AMOUNT,

    B.PATIENT_PAYABLE_AMOUNT,

    UPPER(TRIM(B.PAYMENT_STATUS)),

    UPPER(TRIM(B.PAYMENT_MODE)),

    CURRENT_TIMESTAMP()

FROM CURATED.CUR_BILLING B

INNER JOIN FACT_ADMISSION A
    ON B.ADMISSION_ID = A.ADMISSION_ID

WHERE B.BILL_ID IS NOT NULL;