-- ============================================================
-- File       : fact_prescription.sql
-- Purpose    : Create Prescription Fact Table
-- Layer      : ANALYTICS
-- Grain      : One row per prescription
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE FACT_PRESCRIPTION (
    PRESCRIPTION_KEY NUMBER AUTOINCREMENT,
    PRESCRIPTION_ID NUMBER,

    ADMISSION_KEY NUMBER,
    PATIENT_KEY NUMBER,
    DRUG_KEY NUMBER,

    DOSAGE VARCHAR(50),
    FREQUENCY VARCHAR(50),
    DURATION_DAYS NUMBER,

    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO FACT_PRESCRIPTION (
    PRESCRIPTION_ID,
    ADMISSION_KEY,
    PATIENT_KEY,
    DRUG_KEY,
    DOSAGE,
    FREQUENCY,
    DURATION_DAYS,
    LOAD_TIMESTAMP
)
SELECT
    P.PRESCRIPTION_ID,

    A.ADMISSION_KEY,

    A.PATIENT_KEY,

    D.DRUG_KEY,

    TRIM(P.DOSAGE),

    UPPER(TRIM(P.FREQUENCY)),

    P.DURATION_DAYS,

    CURRENT_TIMESTAMP()

FROM CURATED.CUR_PRESCRIPTION P

INNER JOIN FACT_ADMISSION A
    ON P.ADMISSION_ID = A.ADMISSION_ID

INNER JOIN DIM_DRUG D
    ON P.DRUG_ID = D.DRUG_ID

WHERE P.PRESCRIPTION_ID IS NOT NULL;
