-- ============================================================
-- File       : fact_admission.sql
-- Purpose    : Create Admission Fact Table
-- Layer      : ANALYTICS
-- Grain      : One row per hospital admission
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE FACT_ADMISSION (
    ADMISSION_KEY NUMBER AUTOINCREMENT,
    ADMISSION_ID NUMBER,

    PATIENT_KEY NUMBER,
    DEPARTMENT_KEY NUMBER,
    DISEASE_KEY NUMBER,
    WARD_KEY NUMBER,

    ADMISSION_DATE_KEY NUMBER(8,0),
    DISCHARGE_DATE_KEY NUMBER(8,0),

    BED_ID NUMBER,
    ADMISSION_STATUS VARCHAR(30),
    ADMISSION_TYPE VARCHAR(30),

    LENGTH_OF_STAY NUMBER,

    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO FACT_ADMISSION (
    ADMISSION_ID,
    PATIENT_KEY,
    DEPARTMENT_KEY,
    DISEASE_KEY,
    WARD_KEY,
    ADMISSION_DATE_KEY,
    DISCHARGE_DATE_KEY,
    BED_ID,
    ADMISSION_STATUS,
    ADMISSION_TYPE,
    LENGTH_OF_STAY,
    LOAD_TIMESTAMP
)
SELECT
    A.ADMISSION_ID,

    P.PATIENT_KEY,
    DP.DEPARTMENT_KEY,
    DS.DISEASE_KEY,
    W.WARD_KEY,

    TO_NUMBER(TO_CHAR(A.ADMISSION_DATE, 'YYYYMMDD')),

    CASE
        WHEN A.DISCHARGE_DATE IS NOT NULL
        THEN TO_NUMBER(TO_CHAR(A.DISCHARGE_DATE, 'YYYYMMDD'))
    END,

    A.BED_ID,

    UPPER(TRIM(A.ADMISSION_STATUS)),

    UPPER(TRIM(A.ADMISSION_TYPE)),

    CASE
        WHEN A.DISCHARGE_DATE IS NOT NULL
        THEN DATEDIFF(
            DAY,
            A.ADMISSION_DATE,
            A.DISCHARGE_DATE
        )
    END,

    CURRENT_TIMESTAMP()

FROM CURATED.CUR_ADMISSION A

INNER JOIN DIM_PATIENT P
    ON A.PATIENT_ID = P.PATIENT_ID

INNER JOIN DIM_DEPARTMENT DP
    ON A.DEPARTMENT_ID = DP.DEPARTMENT_ID

INNER JOIN DIM_DISEASE DS
    ON A.DISEASE_ID = DS.DISEASE_ID

INNER JOIN DIM_WARD W
    ON A.WARD_ID = W.WARD_ID

WHERE A.ADMISSION_ID IS NOT NULL;