SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT ADMISSION_ID) AS UNIQUE_ADMISSIONS,
    COUNT(DISTINCT ADMISSION_KEY) AS UNIQUE_ADMISSION_KEYS
FROM ANALYTICS.FACT_ADMISSION;

SELECT COUNT(*) AS INVALID_PATIENT_KEYS
FROM FACT_ADMISSION F
LEFT JOIN DIM_PATIENT P
    ON F.PATIENT_KEY = P.PATIENT_KEY
WHERE P.PATIENT_KEY IS NULL;


SELECT COUNT(*) AS INVALID_DEPARTMENT_KEYS
FROM FACT_ADMISSION F
LEFT JOIN DIM_DEPARTMENT D
    ON F.DEPARTMENT_KEY = D.DEPARTMENT_KEY
WHERE D.DEPARTMENT_KEY IS NULL;


SELECT COUNT(*) AS INVALID_DISEASE_KEYS
FROM FACT_ADMISSION F
LEFT JOIN DIM_DISEASE D
    ON F.DISEASE_KEY = D.DISEASE_KEY
WHERE D.DISEASE_KEY IS NULL;


SELECT COUNT(*) AS INVALID_WARD_KEYS
FROM FACT_ADMISSION F
LEFT JOIN DIM_WARD W
    ON F.WARD_KEY = W.WARD_KEY
WHERE W.WARD_KEY IS NULL;


SELECT
    COUNT_IF(ADMISSION_DATE_KEY IS NULL) AS NULL_ADMISSION_DATES,
    COUNT_IF(
        DISCHARGE_DATE_KEY IS NOT NULL
        AND DISCHARGE_DATE_KEY < ADMISSION_DATE_KEY
    ) AS INVALID_DISCHARGE_DATES,
    COUNT_IF(LENGTH_OF_STAY < 0) AS INVALID_LENGTH_OF_STAY
FROM FACT_ADMISSION;


SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT BILL_ID) AS UNIQUE_BILLS
FROM CURATED.CUR_BILLING;


SELECT COUNT(*) AS ORPHAN_ADMISSIONS
FROM CURATED.CUR_BILLING B
LEFT JOIN ANALYTICS.FACT_ADMISSION A
    ON B.ADMISSION_ID = A.ADMISSION_ID
WHERE A.ADMISSION_ID IS NULL;


SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT BILL_ID) AS UNIQUE_BILLS,
    COUNT(DISTINCT BILLING_KEY) AS UNIQUE_BILLING_KEYS
FROM ANALYTICS.FACT_BILLING;


SELECT COUNT(*) AS INVALID_ADMISSION_KEYS
FROM FACT_BILLING B
LEFT JOIN FACT_ADMISSION A
    ON B.ADMISSION_KEY = A.ADMISSION_KEY
WHERE A.ADMISSION_KEY IS NULL;


SELECT COUNT(*) AS INVALID_PATIENT_KEYS
FROM FACT_BILLING B
LEFT JOIN DIM_PATIENT P
    ON B.PATIENT_KEY = P.PATIENT_KEY
WHERE P.PATIENT_KEY IS NULL;


SELECT
    COUNT(*) AS TOTAL_BILLS,
    COUNT_IF(
        ROUND(
            INSURANCE_COVERED_AMOUNT + PATIENT_PAYABLE_AMOUNT,
            2
        ) = ROUND(TOTAL_AMOUNT, 2)
    ) AS VALID_BILLS,
    COUNT_IF(
        ROUND(
            INSURANCE_COVERED_AMOUNT + PATIENT_PAYABLE_AMOUNT,
            2
        ) <> ROUND(TOTAL_AMOUNT, 2)
    ) AS INVALID_BILLS
FROM FACT_BILLING;


SELECT
    COUNT_IF(TOTAL_AMOUNT < 0) AS INVALID_TOTAL,
    COUNT_IF(INSURANCE_COVERED_AMOUNT < 0) AS INVALID_INSURANCE,
    COUNT_IF(PATIENT_PAYABLE_AMOUNT < 0) AS INVALID_PATIENT_PAYABLE
FROM FACT_BILLING;