SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT ADMISSION_ID) AS UNIQUE_ADMISSIONS,
    COUNT(DISTINCT ADMISSION_KEY) AS UNIQUE_ADMISSION_KEYS
FROM ANALYTICS.FACT_ADMISSION;

SELECT COUNT(*) AS INVALID_PATIENT_KEYS
FROM FACT_ADMISSION F
LEFT JOIN DIM_PATIENT P
    ON F.PATIENT_KEY = P.PATIENT_KEY
WHERE P.PATIENT_KEY IS NULL;


SELECT COUNT(*) AS INVALID_DEPARTMENT_KEYS
FROM FACT_ADMISSION F
LEFT JOIN DIM_DEPARTMENT D
    ON F.DEPARTMENT_KEY = D.DEPARTMENT_KEY
WHERE D.DEPARTMENT_KEY IS NULL;


SELECT COUNT(*) AS INVALID_DISEASE_KEYS
FROM FACT_ADMISSION F
LEFT JOIN DIM_DISEASE D
    ON F.DISEASE_KEY = D.DISEASE_KEY
WHERE D.DISEASE_KEY IS NULL;


SELECT COUNT(*) AS INVALID_WARD_KEYS
FROM FACT_ADMISSION F
LEFT JOIN DIM_WARD W
    ON F.WARD_KEY = W.WARD_KEY
WHERE W.WARD_KEY IS NULL;


SELECT
    COUNT_IF(ADMISSION_DATE_KEY IS NULL) AS NULL_ADMISSION_DATES,
    COUNT_IF(
        DISCHARGE_DATE_KEY IS NOT NULL
        AND DISCHARGE_DATE_KEY < ADMISSION_DATE_KEY
    ) AS INVALID_DISCHARGE_DATES,
    COUNT_IF(LENGTH_OF_STAY < 0) AS INVALID_LENGTH_OF_STAY
FROM FACT_ADMISSION;