-- ============================================================
-- File       : dim_patient.sql
-- Purpose    : Create Patient Dimension
-- Layer      : ANALYTICS
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE DIM_PATIENT (
    PATIENT_KEY NUMBER AUTOINCREMENT,
    PATIENT_ID NUMBER,
    GENDER VARCHAR(10),
    DATE_OF_BIRTH DATE,
    BLOOD_GROUP VARCHAR(5),
    CITY VARCHAR(100),
    CONTACT_NUMBER VARCHAR(50),
    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO DIM_PATIENT (
    PATIENT_ID,
    GENDER,
    DATE_OF_BIRTH,
    BLOOD_GROUP,
    CITY,
    CONTACT_NUMBER,
    LOAD_TIMESTAMP
)
SELECT
    PATIENT_ID,
    GENDER,
    DATE_OF_BIRTH,
    BLOOD_GROUP,
    CITY,
    CONTACT_NUMBER,
    LOAD_TIMESTAMP
FROM CURATED.CUR_PATIENT
WHERE PATIENT_ID IS NOT NULL;


