-- ============================================================
-- File       : dim_insurance_provider.sql
-- Purpose    : Create Insurance Provider Dimension
-- Layer      : ANALYTICS
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE DIM_INSURANCE_PROVIDER (
    INSURANCE_PROVIDER_KEY NUMBER AUTOINCREMENT,
    INSURANCE_PROVIDER_ID NUMBER,
    PROVIDER_NAME VARCHAR(150),
    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO DIM_INSURANCE_PROVIDER (
    INSURANCE_PROVIDER_ID,
    PROVIDER_NAME,
    LOAD_TIMESTAMP
)
SELECT
    INSURANCE_PROVIDER_ID,
    TRIM(PROVIDER_NAME),
    CURRENT_TIMESTAMP()
FROM RAW.RAW_INSURANCE_PROVIDER
WHERE INSURANCE_PROVIDER_ID IS NOT NULL;