SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT DOCTOR_ID) AS UNIQUE_DOCTORS,
    COUNT(DISTINCT DOCTOR_KEY) AS UNIQUE_DOCTOR_KEYS
FROM ANALYTICS.DIM_DOCTOR;


SELECT COUNT(*) AS ORPHAN_DEPARTMENTS
FROM ANALYTICS.DIM_DOCTOR D
LEFT JOIN ANALYTICS.DIM_DEPARTMENT DP
    ON D.DEPARTMENT_ID = DP.DEPARTMENT_ID
WHERE DP.DEPARTMENT_ID IS NULL;

SELECT *
FROM ANALYTICS.DIM_DOCTOR
ORDER BY DOCTOR_KEY
LIMIT 10;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT DISEASE_ID) AS UNIQUE_DISEASES
FROM RAW.RAW_DISEASE;

SELECT COUNT(*) AS NULL_DISEASE_NAMES
FROM RAW.RAW_DISEASE
WHERE DISEASE_NAME IS NULL;

SELECT COUNT(*) AS ORPHAN_DISEASES
FROM RAW.RAW_ADMISSION A
LEFT JOIN RAW.RAW_DISEASE D
    ON A.DISEASE_ID = D.DISEASE_ID
WHERE D.DISEASE_ID IS NULL;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT DISEASE_ID) AS UNIQUE_DISEASES,
    COUNT(DISTINCT DISEASE_KEY) AS UNIQUE_DISEASE_KEYS
FROM ANALYTICS.DIM_DISEASE;


SELECT *
FROM ANALYTICS.DIM_DISEASE
ORDER BY DISEASE_KEY;

SELECT COUNT(*) AS ORPHAN_DISEASES
FROM ANALYTICS.DIM_DISEASE D
JOIN ANALYTICS.FACT_ADMISSION F
    ON D.DISEASE_KEY = F.DISEASE_KEY;


SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT WARD_ID) AS UNIQUE_WARDS
FROM RAW.RAW_WARD;

SELECT COUNT(*) AS ORPHAN_DEPARTMENTS
FROM RAW.RAW_WARD W
LEFT JOIN RAW.RAW_DEPARTMENT D
    ON W.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID IS NULL;


SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT WARD_ID) AS UNIQUE_WARDS,
    COUNT(DISTINCT WARD_KEY) AS UNIQUE_WARD_KEYS
FROM ANALYTICS.DIM_WARD;


SELECT *
FROM ANALYTICS.DIM_WARD
ORDER BY WARD_KEY;

SELECT COUNT(*) AS ORPHAN_DEPARTMENTS
FROM ANALYTICS.DIM_WARD W
LEFT JOIN ANALYTICS.DIM_DEPARTMENT D
    ON W.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID IS NULL;


SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT DRUG_ID) AS UNIQUE_DRUGS
FROM RAW.RAW_DRUG;


SELECT COUNT(*) AS ORPHAN_MANUFACTURERS
FROM RAW.RAW_DRUG D
LEFT JOIN RAW.RAW_DRUG_MANUFACTURER M
    ON D.MANUFACTURER_ID = M.MANUFACTURER_ID
WHERE M.MANUFACTURER_ID IS NULL;


SELECT
    COUNT(*) AS TOTAL_MANUFACTURERS,
    COUNT(DISTINCT MANUFACTURER_ID) AS UNIQUE_MANUFACTURERS
FROM RAW.RAW_DRUG_MANUFACTURER;


SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT DRUG_ID) AS UNIQUE_DRUGS,
    COUNT(DISTINCT DRUG_KEY) AS UNIQUE_DRUG_KEYS
FROM ANALYTICS.DIM_DRUG;


SELECT
    COUNT_IF(DRUG_NAME IS NULL) AS NULL_DRUG_NAMES,
    COUNT_IF(BRAND_NAME IS NULL) AS NULL_BRAND_NAMES,
    COUNT_IF(DRUG_CATEGORY IS NULL) AS NULL_CATEGORIES,
    COUNT_IF(UNIT_COST IS NULL) AS NULL_COSTS,
    COUNT_IF(MANUFACTURER_NAME IS NULL) AS NULL_MANUFACTURERS
FROM ANALYTICS.DIM_DRUG;

SELECT *
FROM ANALYTICS.DIM_DRUG
ORDER BY DRUG_KEY
LIMIT 10;


SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT INSURANCE_PROVIDER_ID) AS UNIQUE_PROVIDERS
FROM RAW.RAW_INSURANCE_PROVIDER;


SELECT COUNT(*) AS NULL_PROVIDER_NAMES
FROM RAW.RAW_INSURANCE_PROVIDER
WHERE PROVIDER_NAME IS NULL;


SELECT COUNT(*) AS ORPHAN_PROVIDERS
FROM RAW.RAW_PATIENT_INSURANCE PI
LEFT JOIN RAW.RAW_INSURANCE_PROVIDER IP
    ON PI.INSURANCE_PROVIDER_ID = IP.INSURANCE_PROVIDER_ID
WHERE IP.INSURANCE_PROVIDER_ID IS NULL;


SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT INSURANCE_PROVIDER_ID) AS UNIQUE_PROVIDERS,
    COUNT(DISTINCT INSURANCE_PROVIDER_KEY) AS UNIQUE_PROVIDER_KEYS
FROM ANALYTICS.DIM_INSURANCE_PROVIDER;


SELECT *
FROM ANALYTICS.DIM_INSURANCE_PROVIDER
ORDER BY INSURANCE_PROVIDER_KEY;


SELECT *
FROM ANALYTICS.DIM_INSURANCE_PROVIDER
WHERE PROVIDER_NAME IS NULL;

DESC TABLE RAW.RAW_DIAGNOSTIC_TEST;


SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT TEST_ID) AS UNIQUE_TESTS,
    COUNT(DISTINCT TEST_KEY) AS UNIQUE_TEST_KEYS
FROM ANALYTICS.DIM_DIAGNOSTIC_TEST;


SELECT
    COUNT_IF(TEST_NAME IS NULL) AS NULL_TEST_NAMES,
    COUNT_IF(TEST_CATEGORY IS NULL) AS NULL_TEST_CATEGORIES,
    COUNT_IF(STANDARD_COST IS NULL) AS NULL_COSTS
FROM ANALYTICS.DIM_DIAGNOSTIC_TEST;


SELECT COUNT(*) AS ORPHAN_DEPARTMENTS
FROM ANALYTICS.DIM_DIAGNOSTIC_TEST T
LEFT JOIN ANALYTICS.DIM_DEPARTMENT D
    ON T.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID IS NULL;


SELECT *
FROM ANALYTICS.DIM_DIAGNOSTIC_TEST
ORDER BY TEST_KEY
LIMIT 10;