USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS HEALTHCARE_ADMIN;

CREATE ROLE IF NOT EXISTS HEALTHCARE_ANALYST;

GRANT ROLE HEALTHCARE_ADMIN TO ROLE ACCOUNTADMIN;

GRANT ROLE HEALTHCARE_ANALYST TO ROLE ACCOUNTADMIN;

