USE ROLE ACCOUNTADMIN;

-- Warehouse access
GRANT USAGE ON WAREHOUSE HEALTHCARE_WH
TO ROLE HEALTHCARE_ANALYST;

-- Database access
GRANT USAGE ON DATABASE HEALTHCARE_DW
TO ROLE HEALTHCARE_ANALYST;

-- Analytics schema access
GRANT USAGE ON SCHEMA HEALTHCARE_DW.ANALYTICS
TO ROLE HEALTHCARE_ANALYST;

-- Existing tables
GRANT SELECT ON ALL TABLES IN SCHEMA HEALTHCARE_DW.ANALYTICS
TO ROLE HEALTHCARE_ANALYST;

-- Existing views
GRANT SELECT ON ALL VIEWS IN SCHEMA HEALTHCARE_DW.ANALYTICS
TO ROLE HEALTHCARE_ANALYST;

-- Future tables
GRANT SELECT ON FUTURE TABLES
IN SCHEMA HEALTHCARE_DW.ANALYTICS
TO ROLE HEALTHCARE_ANALYST;

-- Future views
GRANT SELECT ON FUTURE VIEWS
IN SCHEMA HEALTHCARE_DW.ANALYTICS
TO ROLE HEALTHCARE_ANALYST;