USE ROLE HEALTHCARE_ANALYST;
USE SECONDARY ROLES NONE;


SELECT *
FROM HEALTHCARE_DW.ANALYTICS.DIM_PATIENT
LIMIT 5;


SELECT *
FROM HEALTHCARE_DW.RAW.RAW_PATIENT
LIMIT 5;


USE ROLE ACCOUNTADMIN;


USE ROLE ACCOUNTADMIN;

SELECT
    PATIENT_ID,
    CONTACT_NUMBER
FROM HEALTHCARE_DW.ANALYTICS.DIM_PATIENT
LIMIT 5;


USE ROLE HEALTHCARE_ANALYST;

USE SECONDARY ROLES NONE;

SELECT
    PATIENT_ID,
    CONTACT_NUMBER
FROM HEALTHCARE_DW.ANALYTICS.DIM_PATIENT
LIMIT 5;



USE ROLE HEALTHCARE_ANALYST;

USE SECONDARY ROLES NONE;

USE WAREHOUSE HEALTHCARE_WH;

SELECT
    PATIENT_INSURANCE_ID,
    POLICY_NUMBER,
    COVERAGE_PERCENTAGE
FROM HEALTHCARE_DW.ANALYTICS.BRIDGE_PATIENT_INSURANCE
LIMIT 10;



USE ROLE ACCOUNTADMIN;

SELECT
    PATIENT_INSURANCE_ID,
    POLICY_NUMBER,
    COVERAGE_PERCENTAGE
FROM HEALTHCARE_DW.ANALYTICS.BRIDGE_PATIENT_INSURANCE
LIMIT 10;



USE ROLE ACCOUNTADMIN;

SELECT
    POLICY_NAME,
    POLICY_KIND
FROM HEALTHCARE_DW.INFORMATION_SCHEMA.POLICIES
WHERE POLICY_SCHEMA = 'SECURITY'
ORDER BY POLICY_NAME;