
USE ROLE ACCOUNTADMIN;

SELECT COUNT(*) AS PATIENT_COUNT
FROM HEALTHCARE_DW.CURATED.CUR_PATIENT;

INSERT INTO HEALTHCARE_DW.CURATED.CUR_PATIENT (
    PATIENT_ID,
    GENDER,
    DATE_OF_BIRTH,
    BLOOD_GROUP,
    CITY,
    CONTACT_NUMBER,
    LOAD_TIMESTAMP
)
VALUES (
    3001,
    'Male',
    '1995-05-15',
    'O+',
    'Hyderabad',
    '+91-9000000001',
    CURRENT_TIMESTAMP()
);


SELECT
    PATIENT_ID,
    METADATA$ACTION,
    METADATA$ISUPDATE
FROM HEALTHCARE_DW.CURATED.STREAM_CUR_PATIENT
WHERE PATIENT_ID = 3001;


EXECUTE TASK HEALTHCARE_DW.ANALYTICS.TASK_DIM_PATIENT;


SELECT *
FROM HEALTHCARE_DW.ANALYTICS.DIM_PATIENT
WHERE PATIENT_ID = 3001;


