-- ============================================================
-- File       : billing_detail.sql
-- Purpose    : Create and Load Curated Billing Detail Table
-- Layer      : CURATED
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE CUR_BILLING_DETAIL (
    BILLING_DETAIL_ID NUMBER,
    CHARGE_TYPE VARCHAR(100),
    REFERENCE_ID NUMBER,
    AMOUNT NUMBER(12,2),
    BILL_ID NUMBER,
    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO CUR_BILLING_DETAIL (
    BILLING_DETAIL_ID,
    CHARGE_TYPE,
    REFERENCE_ID,
    AMOUNT,
    BILL_ID,
    LOAD_TIMESTAMP
)
SELECT
    BILLING_DETAIL_ID,

    TRIM(CHARGE_TYPE) AS CHARGE_TYPE,

    REFERENCE_ID,

    AMOUNT,

    BILL_ID,

    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP

FROM RAW.RAW_BILLING_DETAIL

WHERE BILLING_DETAIL_ID IS NOT NULL;



SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT PATIENT_INSURANCE_ID) AS UNIQUE_POLICIES
FROM RAW.RAW_PATIENT_INSURANCE;

SELECT COUNT(*) AS ORPHAN_PATIENTS
FROM RAW.RAW_PATIENT_INSURANCE PI
LEFT JOIN RAW.RAW_PATIENT P
    ON PI.PATIENT_ID = P.PATIENT_ID
WHERE P.PATIENT_ID IS NULL;


SELECT COUNT(*) AS ORPHAN_PROVIDERS
FROM RAW.RAW_PATIENT_INSURANCE PI
LEFT JOIN RAW.RAW_INSURANCE_PROVIDER IP
    ON PI.INSURANCE_PROVIDER_ID = IP.INSURANCE_PROVIDER_ID
WHERE IP.INSURANCE_PROVIDER_ID IS NULL;


SELECT
    MIN(COVERAGE_PERCENTAGE) AS MIN_COVERAGE,
    MAX(COVERAGE_PERCENTAGE) AS MAX_COVERAGE,
    COUNT_IF(COVERAGE_PERCENTAGE < 0 OR COVERAGE_PERCENTAGE > 100)
        AS INVALID_COVERAGE
FROM RAW.RAW_PATIENT_INSURANCE;