-- ============================================================
-- File       : patient_insurance.sql
-- Purpose    : Create and Load Curated Patient Insurance Table
-- Layer      : CURATED
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE CUR_PATIENT_INSURANCE (
    PATIENT_INSURANCE_ID NUMBER,
    PATIENT_ID NUMBER,
    INSURANCE_PROVIDER_ID NUMBER,
    POLICY_NUMBER VARCHAR(100),
    COVERAGE_PERCENTAGE NUMBER(5,2),
    POLICY_START_DATE DATE,
    POLICY_END_DATE DATE,
    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO CUR_PATIENT_INSURANCE (
    PATIENT_INSURANCE_ID,
    PATIENT_ID,
    INSURANCE_PROVIDER_ID,
    POLICY_NUMBER,
    COVERAGE_PERCENTAGE,
    POLICY_START_DATE,
    POLICY_END_DATE,
    LOAD_TIMESTAMP
)
SELECT
    PATIENT_INSURANCE_ID,

    PATIENT_ID,

    INSURANCE_PROVIDER_ID,

    TRIM(POLICY_NUMBER),

    COVERAGE_PERCENTAGE,

    TRY_TO_DATE(POLICY_START_DATE),

    TRY_TO_DATE(POLICY_END_DATE),

    CURRENT_TIMESTAMP()

FROM RAW.RAW_PATIENT_INSURANCE

WHERE PATIENT_INSURANCE_ID IS NOT NULL;


SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT PATIENT_INSURANCE_ID) AS UNIQUE_POLICIES
FROM CURATED.CUR_PATIENT_INSURANCE;

SELECT
    MIN(COVERAGE_PERCENTAGE) AS MIN_COVERAGE,
    MAX(COVERAGE_PERCENTAGE) AS MAX_COVERAGE,
    COUNT_IF(
        COVERAGE_PERCENTAGE < 0
        OR COVERAGE_PERCENTAGE > 100
    ) AS INVALID_COVERAGE
FROM CURATED.CUR_PATIENT_INSURANCE;

SELECT
    COUNT_IF(POLICY_START_DATE IS NULL) AS INVALID_START_DATES,
    COUNT_IF(POLICY_END_DATE IS NULL) AS INVALID_END_DATES
FROM CURATED.CUR_PATIENT_INSURANCE;


SELECT *
FROM CURATED.CUR_PATIENT_INSURANCE
LIMIT 10;