-- ============================================================
-- File       : patient.sql
-- Purpose    : Create and Load Curated Patient Table
-- Layer      : CURATED
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE CUR_PATIENT (
    PATIENT_ID NUMBER,
    GENDER VARCHAR(10),
    DATE_OF_BIRTH DATE,
    BLOOD_GROUP VARCHAR(5),
    CITY VARCHAR(100),
    CONTACT_NUMBER VARCHAR(50),
    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO CUR_PATIENT (
    PATIENT_ID,
    GENDER,
    DATE_OF_BIRTH,
    BLOOD_GROUP,
    CITY,
    CONTACT_NUMBER,
    LOAD_TIMESTAMP
)
SELECT
    PATIENT_ID,
    INITCAP(TRIM(GENDER)),
    TRY_TO_DATE(DATE_OF_BIRTH),
    UPPER(TRIM(BLOOD_GROUP)),
    TRIM(CITY),
    TRIM(CONTACT_NUMBER),
    CURRENT_TIMESTAMP()
FROM RAW.RAW_PATIENT
WHERE PATIENT_ID IS NOT NULL;


SELECT *
FROM RAW.RAW_ADMISSION
LIMIT 10;