-- ============================================================
-- File       : patient_diagnostic.sql
-- Purpose    : Create and Load Curated Patient Diagnostic Table
-- Layer      : CURATED
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE CUR_PATIENT_DIAGNOSTIC (
    PATIENT_DIAGNOSTIC_ID NUMBER,
    TEST_DATE DATE,
    RESULT_STATUS VARCHAR(30),
    ADMISSION_ID NUMBER,
    TEST_ID NUMBER,
    DOCTOR_ID NUMBER,
    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO CUR_PATIENT_DIAGNOSTIC (
    PATIENT_DIAGNOSTIC_ID,
    TEST_DATE,
    RESULT_STATUS,
    ADMISSION_ID,
    TEST_ID,
    DOCTOR_ID,
    LOAD_TIMESTAMP
)
SELECT
    PATIENT_DIAGNOSTIC_ID,

    TRY_TO_DATE(TEST_DATE) AS TEST_DATE,

    UPPER(TRIM(RESULT_STATUS)) AS RESULT_STATUS,

    ADMISSION_ID,

    TEST_ID,

    DOCTOR_ID,

    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP

FROM RAW.RAW_PATIENT_DIAGNOSTIC

WHERE PATIENT_DIAGNOSTIC_ID IS NOT NULL;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT BILLING_DETAIL_ID) AS UNIQUE_DETAILS
FROM RAW.RAW_BILLING_DETAIL;


SELECT COUNT(*) AS ORPHAN_BILLS
FROM RAW.RAW_BILLING_DETAIL BD
LEFT JOIN RAW.RAW_BILLING B
    ON BD.BILL_ID = B.BILL_ID
WHERE B.BILL_ID IS NULL;

SELECT
    MIN(AMOUNT) AS MIN_AMOUNT,
    MAX(AMOUNT) AS MAX_AMOUNT,
    COUNT_IF(AMOUNT < 0) AS NEGATIVE_AMOUNTS
FROM RAW.RAW_BILLING_DETAIL;