-- ============================================================
-- File       : dim_date.sql
-- Purpose    : Create Date Dimension
-- Layer      : ANALYTICS
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY NUMBER(8,0),
    FULL_DATE DATE,
    DAY_OF_MONTH NUMBER(2,0),
    DAY_NAME VARCHAR(10),
    DAY_OF_WEEK NUMBER(1,0),
    WEEK_OF_YEAR NUMBER(2,0),
    MONTH_NUMBER NUMBER(2,0),
    MONTH_NAME VARCHAR(10),
    QUARTER_NUMBER NUMBER(1,0),
    YEAR_NUMBER NUMBER(4,0),
    IS_WEEKEND BOOLEAN
);

INSERT INTO DIM_DATE
SELECT
    TO_NUMBER(TO_CHAR(DATE_VALUE, 'YYYYMMDD')) AS DATE_KEY,
    DATE_VALUE AS FULL_DATE,
    DAY(DATE_VALUE) AS DAY_OF_MONTH,
    DAYNAME(DATE_VALUE) AS DAY_NAME,
    DAYOFWEEK(DATE_VALUE) AS DAY_OF_WEEK,
    WEEKOFYEAR(DATE_VALUE) AS WEEK_OF_YEAR,
    MONTH(DATE_VALUE) AS MONTH_NUMBER,
    MONTHNAME(DATE_VALUE) AS MONTH_NAME,
    QUARTER(DATE_VALUE) AS QUARTER_NUMBER,
    YEAR(DATE_VALUE) AS YEAR_NUMBER,
    CASE
        WHEN DAYOFWEEK(DATE_VALUE) IN (1, 7)
        THEN TRUE
        ELSE FALSE
    END AS IS_WEEKEND
FROM (
    SELECT DATEADD(
        DAY,
        SEQ4(),
        '2020-01-01'::DATE
    ) AS DATE_VALUE
    FROM TABLE(GENERATOR(ROWCOUNT => 3653))
);

