-- ============================================================
-- File       : dim_drug.sql
-- Purpose    : Create Drug Dimension
-- Layer      : ANALYTICS
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE DIM_DRUG (
    DRUG_KEY NUMBER AUTOINCREMENT,
    DRUG_ID NUMBER,
    DRUG_NAME VARCHAR(100),
    BRAND_NAME VARCHAR(100),
    DRUG_CATEGORY VARCHAR(50),
    UNIT_COST NUMBER(10,2),
    MANUFACTURER_ID NUMBER,
    MANUFACTURER_NAME VARCHAR(150),
    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO DIM_DRUG (
    DRUG_ID,
    DRUG_NAME,
    BRAND_NAME,
    DRUG_CATEGORY,
    UNIT_COST,
    MANUFACTURER_ID,
    MANUFACTURER_NAME,
    LOAD_TIMESTAMP
)
SELECT
    D.DRUG_ID,
    TRIM(D.DRUG_NAME),
    TRIM(D.BRAND_NAME),
    TRIM(D.DRUG_CATEGORY),
    D.UNIT_COST,
    D.MANUFACTURER_ID,
    TRIM(M.MANUFACTURER_NAME),
    CURRENT_TIMESTAMP()
FROM RAW.RAW_DRUG D
INNER JOIN RAW.RAW_DRUG_MANUFACTURER M
    ON D.MANUFACTURER_ID = M.MANUFACTURER_ID
WHERE D.DRUG_ID IS NOT NULL;