-- ============================================================
-- File       : dim_doctor.sql
-- Purpose    : Create Doctor Dimension
-- Layer      : ANALYTICS
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE DIM_DOCTOR (
    DOCTOR_KEY NUMBER AUTOINCREMENT,
    DOCTOR_ID NUMBER,
    EMPLOYEE_ID NUMBER,
    DOCTOR_NAME VARCHAR(100),
    GENDER VARCHAR(10),
    SPECIALIZATION VARCHAR(100),
    QUALIFICATION VARCHAR(30),
    EXPERIENCE_YEARS NUMBER,
    EMPLOYMENT_TYPE VARCHAR(30),
    DATE_OF_JOINING DATE,
    DEPARTMENT_ID NUMBER,
    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO DIM_DOCTOR (
    DOCTOR_ID,
    EMPLOYEE_ID,
    DOCTOR_NAME,
    GENDER,
    SPECIALIZATION,
    QUALIFICATION,
    EXPERIENCE_YEARS,
    EMPLOYMENT_TYPE,
    DATE_OF_JOINING,
    DEPARTMENT_ID,
    LOAD_TIMESTAMP
)
SELECT
    DOCTOR_ID,
    EMPLOYEE_ID,
    DOCTOR_NAME,
    GENDER,
    SPECIALIZATION,
    QUALIFICATION,
    EXPERIENCE_YEARS,
    EMPLOYMENT_TYPE,
    DATE_OF_JOINING,
    DEPARTMENT_ID,
    LOAD_TIMESTAMP
FROM CURATED.CUR_DOCTOR
WHERE DOCTOR_ID IS NOT NULL;