-- ============================================================
-- File       : dim_department.sql
-- Purpose    : Create Department Dimension
-- Layer      : ANALYTICS
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE DIM_DEPARTMENT (
    DEPARTMENT_KEY NUMBER AUTOINCREMENT,
    DEPARTMENT_ID NUMBER,
    DEPARTMENT_NAME VARCHAR(100),
    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO DIM_DEPARTMENT (
    DEPARTMENT_ID,
    DEPARTMENT_NAME,
    LOAD_TIMESTAMP
)
SELECT
    DEPARTMENT_ID,
    TRIM(DEPARTMENT_NAME),
    CURRENT_TIMESTAMP()
FROM RAW.RAW_DEPARTMENT
WHERE DEPARTMENT_ID IS NOT NULL;


