-- ============================================================
-- File       : dim_diagnostic_test.sql
-- Purpose    : Create Diagnostic Test Dimension
-- Layer      : ANALYTICS
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE DIM_DIAGNOSTIC_TEST (
    TEST_KEY NUMBER AUTOINCREMENT,
    TEST_ID NUMBER,
    TEST_NAME VARCHAR(100),
    TEST_CATEGORY VARCHAR(50),
    STANDARD_COST NUMBER(10,2),
    DEPARTMENT_ID NUMBER,
    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO DIM_DIAGNOSTIC_TEST (
    TEST_ID,
    TEST_NAME,
    TEST_CATEGORY,
    STANDARD_COST,
    DEPARTMENT_ID,
    LOAD_TIMESTAMP
)
SELECT
    TEST_ID,
    TRIM(TEST_NAME),
    TRIM(TEST_CATEGORY),
    STANDARD_COST,
    DEPARTMENT_ID,
    CURRENT_TIMESTAMP()
FROM RAW.RAW_DIAGNOSTIC_TEST
WHERE TEST_ID IS NOT NULL;