-- ============================================================
-- File       : doctor.sql
-- Purpose    : Create and Load Curated Doctor Table
-- Layer      : CURATED
-- Project    : Healthcare Enterprise Data Warehouse
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE CUR_DOCTOR (
    DOCTOR_ID           NUMBER,
    EMPLOYEE_ID         NUMBER,
    DOCTOR_NAME         VARCHAR(100),
    GENDER              VARCHAR(10),
    SPECIALIZATION      VARCHAR(100),
    QUALIFICATION       VARCHAR(30),
    EXPERIENCE_YEARS    NUMBER,
    EMPLOYMENT_TYPE     VARCHAR(30),
    DATE_OF_JOINING     DATE,
    DEPARTMENT_ID       NUMBER,
    LOAD_TIMESTAMP      TIMESTAMP_NTZ
);

INSERT INTO CUR_DOCTOR (
    DOCTOR_ID,
    EMPLOYEE_ID,
    DOCTOR_NAME,
    GENDER,
    SPECIALIZATION,
    QUALIFICATION,
    EXPERIENCE_YEARS,
    EMPLOYMENT_TYPE,
    DATE_OF_JOINING,
    DEPARTMENT_ID,
    LOAD_TIMESTAMP
)
SELECT
    D.DOCTOR_ID,
    D.EMPLOYEE_ID,
    TRIM(E.EMPLOYEE_NAME) AS DOCTOR_NAME,
    INITCAP(TRIM(E.GENDER)) AS GENDER,
    TRIM(D.SPECIALIZATION) AS SPECIALIZATION,
    UPPER(TRIM(D.QUALIFICATION)) AS QUALIFICATION,
    D.EXPERIENCE_YEARS,
    INITCAP(TRIM(E.EMPLOYMENT_TYPE)) AS EMPLOYMENT_TYPE,
    TRY_TO_DATE(E.DATE_OF_JOINING) AS DATE_OF_JOINING,
    E.DEPARTMENT_ID,
    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP

FROM RAW.RAW_DOCTOR D

INNER JOIN RAW.RAW_EMPLOYEE E
    ON D.EMPLOYEE_ID = E.EMPLOYEE_ID

WHERE D.DOCTOR_ID IS NOT NULL;

SELECT *
FROM CURATED.CUR_DOCTOR
ORDER BY DOCTOR_ID
LIMIT 10;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT DOCTOR_ID) AS UNIQUE_DOCTORS
FROM CURATED.CUR_DOCTOR;