-- ============================================================
-- File       : patient_diagnostic.sql
-- Purpose    : Create and Load Curated Patient Diagnostic Table
-- Layer      : CURATED
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE CUR_PATIENT_DIAGNOSTIC (
    PATIENT_DIAGNOSTIC_ID NUMBER,
    TEST_DATE DATE,
    RESULT_STATUS VARCHAR(30),
    ADMISSION_ID NUMBER,
    TEST_ID NUMBER,
    DOCTOR_ID NUMBER,
    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO CUR_PATIENT_DIAGNOSTIC (
    PATIENT_DIAGNOSTIC_ID,
    TEST_DATE,
    RESULT_STATUS,
    ADMISSION_ID,
    TEST_ID,
    DOCTOR_ID,
    LOAD_TIMESTAMP
)
SELECT
    PATIENT_DIAGNOSTIC_ID,

    TRY_TO_DATE(TEST_DATE) AS TEST_DATE,

    UPPER(TRIM(RESULT_STATUS)) AS RESULT_STATUS,

    ADMISSION_ID,

    TEST_ID,

    DOCTOR_ID,

    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP

FROM RAW.RAW_PATIENT_DIAGNOSTIC

WHERE PATIENT_DIAGNOSTIC_ID IS NOT NULL;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT PATIENT_DIAGNOSTIC_ID) AS UNIQUE_DIAGNOSTICS
FROM CURATED.CUR_PATIENT_DIAGNOSTIC;

SELECT
    TEST_DATE,
    RESULT_STATUS
FROM CURATED.CUR_PATIENT_DIAGNOSTIC
LIMIT 10;

SELECT
    RESULT_STATUS,
    COUNT(*) AS TEST_COUNT
FROM CURATED.CUR_PATIENT_DIAGNOSTIC
GROUP BY RESULT_STATUS
ORDER BY RESULT_STATUS;


SELECT COUNT(*) AS INVALID_TEST_DATES
FROM CURATED.CUR_PATIENT_DIAGNOSTIC
WHERE TEST_DATE IS NULL;