-- ============================================================
-- File       : prescription.sql
-- Purpose    : Create and Load Curated Prescription Table
-- Layer      : CURATED
-- Project    : Healthcare Enterprise Data Warehouse
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE CUR_PRESCRIPTION (
    PRESCRIPTION_ID NUMBER,
    DOSAGE VARCHAR(50),
    FREQUENCY VARCHAR(50),
    DURATION_DAYS NUMBER,
    ADMISSION_ID NUMBER,
    DRUG_ID NUMBER,
    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO CUR_PRESCRIPTION (
    PRESCRIPTION_ID,
    DOSAGE,
    FREQUENCY,
    DURATION_DAYS,
    ADMISSION_ID,
    DRUG_ID,
    LOAD_TIMESTAMP
)
SELECT
    PRESCRIPTION_ID,

    TRIM(DOSAGE) AS DOSAGE,

    UPPER(TRIM(FREQUENCY)) AS FREQUENCY,

    DURATION_DAYS,

    ADMISSION_ID,

    DRUG_ID,

    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP

FROM RAW.RAW_PRESCRIPTION

WHERE PRESCRIPTION_ID IS NOT NULL;


SELECT COUNT(*) AS ORPHAN_ADMISSIONS
FROM RAW.RAW_PATIENT_DIAGNOSTIC PD
LEFT JOIN RAW.RAW_ADMISSION A
    ON PD.ADMISSION_ID = A.ADMISSION_ID
WHERE A.ADMISSION_ID IS NULL;

SELECT COUNT(*) AS ORPHAN_TESTS
FROM RAW.RAW_PATIENT_DIAGNOSTIC PD
LEFT JOIN RAW.RAW_DIAGNOSTIC_TEST DT
    ON PD.TEST_ID = DT.TEST_ID
WHERE DT.TEST_ID IS NULL;

SELECT COUNT(*) AS ORPHAN_DOCTORS
FROM RAW.RAW_PATIENT_DIAGNOSTIC PD
LEFT JOIN RAW.RAW_DOCTOR D
    ON PD.DOCTOR_ID = D.DOCTOR_ID
WHERE D.DOCTOR_ID IS NULL;