-- ============================================================
-- File       : prescription.sql
-- Purpose    : Create and Load Curated Prescription Table
-- Layer      : CURATED
-- Project    : Healthcare Enterprise Data Warehouse
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE CUR_PRESCRIPTION (
    PRESCRIPTION_ID NUMBER,
    DOSAGE VARCHAR(50),
    FREQUENCY VARCHAR(50),
    DURATION_DAYS NUMBER,
    ADMISSION_ID NUMBER,
    DRUG_ID NUMBER,
    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO CUR_PRESCRIPTION (
    PRESCRIPTION_ID,
    DOSAGE,
    FREQUENCY,
    DURATION_DAYS,
    ADMISSION_ID,
    DRUG_ID,
    LOAD_TIMESTAMP
)
SELECT
    PRESCRIPTION_ID,

    TRIM(DOSAGE) AS DOSAGE,

    UPPER(TRIM(FREQUENCY)) AS FREQUENCY,

    DURATION_DAYS,

    ADMISSION_ID,

    DRUG_ID,

    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP

FROM RAW.RAW_PRESCRIPTION

WHERE PRESCRIPTION_ID IS NOT NULL;


SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT PRESCRIPTION_ID) AS UNIQUE_PRESCRIPTIONS
FROM CURATED.CUR_PRESCRIPTION;

SELECT
    FREQUENCY,
    COUNT(*) AS PRESCRIPTION_COUNT
FROM CURATED.CUR_PRESCRIPTION
GROUP BY FREQUENCY
ORDER BY FREQUENCY;