-- ============================================================
-- File       : 02_task_dim_patient.sql
-- Purpose    : Incrementally load DIM_PATIENT
-- Layer      : INCREMENTAL
-- ============================================================

USE ROLE ACCOUNTADMIN;

USE DATABASE HEALTHCARE_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TASK TASK_DIM_PATIENT
    WAREHOUSE = HEALTHCARE_WH
    SCHEDULE = 'USING CRON 0 * * * * UTC'
    WHEN SYSTEM$STREAM_HAS_DATA('HEALTHCARE_DW.CURATED.STREAM_CUR_PATIENT')
AS
MERGE INTO HEALTHCARE_DW.ANALYTICS.DIM_PATIENT AS TARGET
USING (
    SELECT
        PATIENT_ID,
        GENDER,
        DATE_OF_BIRTH,
        BLOOD_GROUP,
        CITY,
        CONTACT_NUMBER,
        LOAD_TIMESTAMP
    FROM HEALTHCARE_DW.CURATED.STREAM_CUR_PATIENT
    WHERE METADATA$ACTION = 'INSERT'
) AS SOURCE
ON TARGET.PATIENT_ID = SOURCE.PATIENT_ID

WHEN MATCHED THEN
    UPDATE SET
        TARGET.GENDER = SOURCE.GENDER,
        TARGET.DATE_OF_BIRTH = SOURCE.DATE_OF_BIRTH,
        TARGET.BLOOD_GROUP = SOURCE.BLOOD_GROUP,
        TARGET.CITY = SOURCE.CITY,
        TARGET.CONTACT_NUMBER = SOURCE.CONTACT_NUMBER,
        TARGET.LOAD_TIMESTAMP = SOURCE.LOAD_TIMESTAMP

WHEN NOT MATCHED THEN
    INSERT (
        PATIENT_ID,
        GENDER,
        DATE_OF_BIRTH,
        BLOOD_GROUP,
        CITY,
        CONTACT_NUMBER,
        LOAD_TIMESTAMP
    )
    VALUES (
        SOURCE.PATIENT_ID,
        SOURCE.GENDER,
        SOURCE.DATE_OF_BIRTH,
        SOURCE.BLOOD_GROUP,
        SOURCE.CITY,
        SOURCE.CONTACT_NUMBER,
        SOURCE.LOAD_TIMESTAMP
    );

