USE ROLE ACCOUNTADMIN;

USE DATABASE HEALTHCARE_DW;
USE SCHEMA CURATED;

DESC TABLE CUR_PATIENT;


SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT PATIENT_ID) AS UNIQUE_PATIENTS
FROM HEALTHCARE_DW.CURATED.CUR_PATIENT;