USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA RAW;

SELECT 'RAW_PATIENT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW_PATIENT
UNION ALL
SELECT 'RAW_ADMISSION', COUNT(*) FROM RAW_ADMISSION
UNION ALL
SELECT 'RAW_BILLING', COUNT(*) FROM RAW_BILLING
UNION ALL
SELECT 'RAW_BILLING_DETAIL', COUNT(*) FROM RAW_BILLING_DETAIL
UNION ALL
SELECT 'RAW_DOCTOR', COUNT(*) FROM RAW_DOCTOR
UNION ALL
SELECT 'RAW_EMPLOYEE', COUNT(*) FROM RAW_EMPLOYEE
UNION ALL
SELECT 'RAW_DEPARTMENT', COUNT(*) FROM RAW_DEPARTMENT
UNION ALL
SELECT 'RAW_DISEASE', COUNT(*) FROM RAW_DISEASE
UNION ALL
SELECT 'RAW_DIAGNOSTIC_TEST', COUNT(*) FROM RAW_DIAGNOSTIC_TEST
UNION ALL
SELECT 'RAW_DRUG', COUNT(*) FROM RAW_DRUG
UNION ALL
SELECT 'RAW_DRUG_INVENTORY', COUNT(*) FROM RAW_DRUG_INVENTORY
UNION ALL
SELECT 'RAW_DRUG_MANUFACTURER', COUNT(*) FROM RAW_DRUG_MANUFACTURER
UNION ALL
SELECT 'RAW_INSURANCE_PROVIDER', COUNT(*) FROM RAW_INSURANCE_PROVIDER
UNION ALL
SELECT 'RAW_PATIENT_DIAGNOSTIC', COUNT(*) FROM RAW_PATIENT_DIAGNOSTIC
UNION ALL
SELECT 'RAW_PATIENT_INSURANCE', COUNT(*) FROM RAW_PATIENT_INSURANCE
UNION ALL
SELECT 'RAW_PRESCRIPTION', COUNT(*) FROM RAW_PRESCRIPTION
UNION ALL
SELECT 'RAW_STAFF_ASSIGNMENT', COUNT(*) FROM RAW_STAFF_ASSIGNMENT
UNION ALL
SELECT 'RAW_WARD', COUNT(*) FROM RAW_WARD
UNION ALL
SELECT 'RAW_BED', COUNT(*) FROM RAW_BED;





